image: node:15.12.0

stages:
  - install
  - lint
  - build

variables:
  CI: 'false'

install_dependencies:
  stage: install
  script:
    - npm install --force
  artifacts:
    paths:
      - node_modules/
  only:
    - merge_requests

lint_check:
  stage: lint
  script:
    - npm run lint
  only:
    - merge_requests

build:
  stage: build
  script:
    - npm run build
  only:
    - merge_requests
